services:
  - type: web
    name: traffic-ai-bangalore
    env: python
    plan: free
    buildCommand: pip install -r backend/backend/backend/requirements.txt
    startCommand: python -m uvicorn backend.backend.backend.app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
